# Generated by Django 2.2.3 on 2019-07-28 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitteraccounts', '0002_auto_20190725_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitteraccount',
            name='twitter_id',
            field=models.CharField(max_length=100),
        ),
    ]
