# Generated by Django 2.2.3 on 2019-07-28 17:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twitteraccounts', '0004_auto_20190728_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitteraccount',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='twitteraccounts', to=settings.AUTH_USER_MODEL),
        ),
    ]
