# Generated by Django 2.2.3 on 2019-07-28 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitteraccounts', '0010_remove_twitteraccount_chainid'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitteraccount',
            name='chainid',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
