# Generated by Django 2.2.3 on 2019-07-10 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrackedTwitterAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twitter_handle', models.CharField(max_length=100)),
                ('twitter_id', models.IntegerField()),
                ('tracking_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
