# Generated by Django 2.2.3 on 2019-07-25 22:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('twitteraccounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitteraccount',
            name='trackers',
            field=models.ManyToManyField(related_name='tracking', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='trackingInfo',
        ),
    ]
