# Generated by Django 2.2.3 on 2019-07-28 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitteraccounts', '0003_auto_20190728_0015'),
    ]

    operations = [
        migrations.RenameField(
            model_name='twitteraccount',
            old_name='twitter_handle',
            new_name='handle',
        ),
        migrations.RenameField(
            model_name='twitteraccount',
            old_name='twitter_id',
            new_name='twitterid',
        ),
        migrations.RemoveField(
            model_name='twitteraccount',
            name='trackers',
        ),
    ]
