# Generated by Django 2.2.3 on 2019-07-28 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitteraccounts', '0008_remove_twitteraccount_chainid'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitteraccount',
            name='chainid',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
