# Generated by Django 2.2.3 on 2019-07-28 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitteraccounts', '0009_twitteraccount_chainid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twitteraccount',
            name='chainid',
        ),
    ]
