# Generated by Django 2.2.3 on 2019-07-19 00:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(max_length=240)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='')),
                ('twitterKey', models.CharField(max_length=240)),
                ('twitterSecret', models.CharField(max_length=240)),
                ('twitterAPIKey', models.CharField(max_length=240)),
                ('twitterAPISecret', models.CharField(max_length=240)),
                ('fctAddress', models.CharField(max_length=240)),
                ('ecAddress', models.CharField(max_length=240)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
