version: '3'

services:
  web:
    build: .
    command: sh -c 
            "python setup.py develop && 
             Scribes runserver 127.0.0.1:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
  
