version: '3'

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    networks:
      - backend

  web:
    build: .
    command: >
      sh -c "python manage.py migrate &&
             python setup.py develop && 
             Scribes runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - backend
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    networks:
      - backend
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - backend
  scribes-faust:
    build: ./twitteraccounts/api/
    command: >
      sh -c "faust -A Scribes_faust worker -l info"
    volumes:
      - .:/app
    depends_on:
      - zookeeper
      - kafka
      - web
    ports:
      - "6066:6066"
      - "9092"
    networks:
      - backend
    restart: on-failure

networks:
  backend:
    driver: bridge
  
