version: '3'

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    networks:
      - backend

  web:
    build: .
    command: >
      sh -c "python manage.py migrate &&
             python setup.py develop && 
             Scribes runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - backend
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    networks:
      - backend
  kafka:
    image: wurstmeister/kafka
    command: [start-kafka.sh]
    ports:
      - "9092:9092"

    expose:
      - "6379"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      FAUST_KAFKA_CONNECT: scribes-faust:9092
      KAFKA_CREATE_TOPICS: "Scribes-faust:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - backend
  scribes-faust:
    build: ./twitteraccounts/api/
    volumes:
      - .:/app
    depends_on:
      - zookeeper
      - kafka
      - web
    ports:
      - "6066:6066"
    networks:
      - backend
    # environment:
    #   # FAUST_KAFKA_CONNECT: kafka:9092
    restart: on-failure

networks:
  backend:
    driver: bridge
  
