version: '3'

services:
  db:
    image: postgres
  web:
    build: .
    command: Scribes runserver 127.0.0.1:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "Scribes_faust:1:2"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  # worker:
  #   build: Dockerfile.dev
  #   context: ./twitteraccounts/api/
  
