# Generated by Django 2.2.3 on 2019-07-11 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ScribeAccount', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScribeCredentials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twitterKey', models.CharField(max_length=240)),
                ('twitterSecret', models.CharField(max_length=240)),
                ('twitterAPIKey', models.CharField(max_length=240)),
                ('twitterAPISecret', models.CharField(max_length=240)),
                ('fctAddress', models.CharField(max_length=240)),
                ('ecAddress', models.CharField(max_length=240)),
                ('scribe_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ScribeAccount.ScribeAccount')),
            ],
        ),
    ]
