# Generated by Django 2.2.3 on 2019-07-11 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ScribeAccount', '0002_scribecredentials'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scribeaccount',
            name='ecAddress',
        ),
        migrations.RemoveField(
            model_name='scribeaccount',
            name='fctAddress',
        ),
        migrations.RemoveField(
            model_name='scribeaccount',
            name='twitterAPIKey',
        ),
        migrations.RemoveField(
            model_name='scribeaccount',
            name='twitterAPISecret',
        ),
        migrations.RemoveField(
            model_name='scribeaccount',
            name='twitterKey',
        ),
        migrations.RemoveField(
            model_name='scribeaccount',
            name='twitterSecret',
        ),
    ]
