# Generated by Django 2.2.3 on 2019-07-11 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ScribeAccount', '0003_auto_20190711_1331'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scribecredentials',
            old_name='scribe_profile',
            new_name='user_profile',
        ),
    ]
