# Generated by Django 2.2.3 on 2019-07-11 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ScribeAccount', '0005_auto_20190711_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scribecredentials',
            name='scribe_profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ScribeAccount.ScribeAccount'),
        ),
    ]
