# Generated by Django 2.2.3 on 2019-07-14 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ScribeAccount', '0006_auto_20190711_1432'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackedTwitterAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twitter_handle', models.CharField(max_length=100)),
                ('twitter_id', models.IntegerField()),
                ('tracking_at', models.DateTimeField(auto_now_add=True)),
                ('scribe_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ScribeAccount.ScribeAccount')),
            ],
        ),
    ]
